### ISSUE TITLE
Does not fire onchange event so (for example) Angular does not up date the model

### ISSUE THREAD

**Issue by robshep** [holyjak/Testofill-chrome-extension#1]
When running the testofill command, the Angular model is not updated because the inputs have not had any UI/Keyboard/Mouse events fired.

This causes an issue when other components of the form depend on the angular model (E.g. invalid form makes button inactive) 

Pull request coming up :)

**Comment by holyjak** [comment]
Hi @robshep, I am so sorry I have overlooked this! I now started to monitor issues properly and shall not overlook any again.

Pls try v8 if this is still relevant for you. And I will look into your PR.

**Comment by holyjak** [comment]
I will close this, the remaining inputs that need fixing are covered by #4.
