### ISSUE TITLE
copie of plugin

### ISSUE THREAD

**Issue by codati** [holyjak/Testofill-chrome-extension#10]
hello,
this plugin seems to be a copy of your work
I don't know if this is normal?

https://chromewebstore.google.com/detail/form-filler-for-testers/anijblpficdhmgfkccpehkdljocalfgo

I don't know if there wouldn't be any modifications that could be harmful

**Comment by holyjak** [comment]
Thank you very much for letting me know! I have reached out to its author and await his response.

**Comment by holyjak** [comment]
The copied plugin has been taken down. Thank you for the report!
