### ISSUE TITLE
$pick throwing an error

### ISSUE THREAD

**Issue by rimselis** [holyjak/Testofill-chrome-extension#8]
Hi,

I'm trying to select / fill an input field with a picked value, but I'm getting an error.
`Error in event handler for runtime.onMessage: TypeError: b.splice is not a function`

My rule looks like this:
```
{
    "query": "[name='nationality']",
    "generate": [
        ["$pick", "LT", "GB", "US", "LV", "DE", "PL", "NL"]
    ]
},
```

**Comment by gezeta-id** [comment]
There's an error in the docs (or maybe chance.js has changed the way pick works). But the correct way to call it is to put the various possibilities into an array:

```javascript
{
    "query": "[name='nationality']",
    "generate": [
        ["$pick", ["LT", "GB", "US", "LV", "DE", "PL", "NL"] ]
    ]
},
```
