### ISSUE TITLE
Autofill File Upload?

### ISSUE THREAD

**Issue by yan-michael** [holyjak/Testofill-chrome-extension#9]
Is there anyway to modify this code to automatically upload a file from a local location to a site?

**Comment by holyjak** [comment]
That is tricky. Do you want to try to implement it?

**Comment by holyjak** [comment]
If you can give me an example how to set the field with JavaScript then I can add it to the extension.

**Comment by yan-michael** [comment]
Sadly, I believe it is impossible, because it would be a pretty big security risk to allow an extension to automatically upload local files.

**Comment by holyjak** [comment]
According to https://stackoverflow.com/questions/21132971/upload-file-as-a-form-data-through-chrome-extension and the existence of the [File system permission](https://support.google.com/chrome/a/answer/7515036?hl=en) it isnt impossible
